- platform: noolite
  channel: 1
  name: "PU112-2"
  type: remote

- platform: noolite
  channel: 7
  name: "PB211"
  type: remote

- platform: noolite
  channel: 8
  name: "PK315"
  type: remote

- platform: noolite
  channel: 60
  name: "PK315"
  type: remote

- platform: noolite
  channel: 10
  name: "PM112 (Motion)"
  type: motion

