# Enables support for tracking state changes over time
history:

system_health:

# View all events in a logbook
logbook:

noolite:
  port: "/dev/ttyUSB0"

automation: !include automations.yaml

light: !include lights.yaml
switch: !include switches.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
fan: !include fans.yaml
