- platform: noolite
  channel: 0
  name: "living_room_light"
  scan_interval: 60
  type: dimmer
  mode: noolite-f

- platform: noolite
  channel: 1
  name: "living_room_work_lights"
  type: dimmer
  mode: noolite-f
  scan_interval: 60
  broadcast: true

- platform: noolite
  channel: 2
  name: "bathroom_light"
  scan_interval: 60
  mode: noolite-f
