- platform: noolite
  channel: 1
  name: "PU112-2 (rgb)"
  type: rgb_remote

- platform: noolite
  channel: 7
  name: "PB211"
  type: remote

- platform: noolite
  channel: 8
  name: "PK315 (1)"
  type: remote

- platform: noolite
  channel: 60
  name: "PK315 (2)"
  type: remote

- platform: noolite
  channel: 9
  name: "PT111"
  type: temp

- platform: noolite
  channel: 9
  name: "PT111"
  type: humi
